name: Tests

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set node version to 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - run: npm install

      - name: Run unit tests
        run: npm run test
